// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HPksH5yhx92LfB9JLZtzNitJwAf6Xgk',
    appId: '1:836178805906:android:d19eb0598d5eb20ee3124b',
    messagingSenderId: '836178805906',
    projectId: 'campi-f8278',
    storageBucket: 'campi-f8278.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVadFa64BpO8BxD55xfP3gwQFpXJ9Zeo',
    appId: '1:836178805906:ios:302259878606b4dae3124b',
    messagingSenderId: '836178805906',
    projectId: 'campi-f8278',
    storageBucket: 'campi-f8278.appspot.com',
    androidClientId: '836178805906-mk4bbsdvckdsl5u6c9s555jugd1vl32q.apps.googleusercontent.com',
    iosClientId: '836178805906-kvhnbc5l7dbucseupmk48vvmngbt52ij.apps.googleusercontent.com',
    iosBundleId: 'com.campi.sns',
  );
}
